### ISSUE TITLE
cron trigger parser is broken

### ISSUE THREAD

**Issue by qmnonic** [funkyfuture/deck-chores#44] opened 2019-02-27 19:32 UTC
**Found in** version 0.2, and still exists in 0.3.

**Description:**
Cron triggers don't work because the code parsing the trigger definition has a bug.

For example, if i specify a cron trigger as documented, or any arrangement of cron statements, it fails with an error.  

2 Examples below:

```
deck-chores    | Deck Chores 0.3 started.
deck-chores    | 2019-02-27 18:05:15,843|INFO    |Inspecting running containers.
deck-chores    | 2019-02-27 18:05:15,857|INFO    |Listening to events.
deck-chores    | 2019-02-27 18:05:15,936|ERROR   |Misconfigured job definition: {'command': '/bin/sh -c "cd /some/path; execute_this"', 'cron': '"0 0 7 3 0"', 'user': 'root', 'name': 'refresh-data'}
deck-chores    | 2019-02-27 18:05:15,936|ERROR   |Errors: {'cron': ['Error while instantiating a CronTrigger with \'(\'*\', \'*\', \'*\', \'"0\', \'0\', \'7\', \'3\', \'0"\')\'.']}
```

```
2019-02-27T16:43:59.269614536Z 2019-02-27 16:43:59,269|ERROR   |Misconfigured job definition: {'command': '/bin/sh -c "cd /some/path; execute_this"', 'cron': '"* * * * * 8 9 0"', 'user': 'root', 'name': 'refresh-data'}
2019-02-27T16:43:59.269992640Z 2019-02-27 16:43:59,269|ERROR   |Errors: {'cron': ['Error while instantiating a CronTrigger with \'(\'"*\', \'*\', \'*\', \'*\', \'*\', \'8\', \'9\', \'0"\')\'.']}
```

I'm not a python dev, but I can see the error is a result of the `_fill_args` function:
```
    def _normalize_coerce_cron(self, value: str) -> Tuple[Type, Tuple[str, ...]]:
        args = self._fill_args(value, CRON_TRIGGER_FIELDS_COUNT, '*')
        return CronTrigger, args
```

Because if i replace it with this, and specify the correct number of cron fields (`* * * * * 8 * *`) it works fine.
```
    def _normalize_coerce_cron(self, value: str) -> Tuple[Type, Tuple[str, ...]]:
        return CronTrigger, value.split(' ')
```

**Comment by funkyfuture** [comment] 2019-02-28 22:28
ciao, how do you configure the container? there are some surplus quotes in this value: `
'"0 0 7 3 0"`'

**Comment by qmnonic** [comment] 2019-03-01 15:04
I tried with quotes `"0 0 7 3 0"`, without quotes `0 0 7 3 0`, individual quotes '"0" "0" "7" "3" "0"` with various styles of cron examples.  None worked.

You'll notice in the logging statements that `_fill_args` doesn't actually prepend `*`s properly in the list/tuple - see the `"` in the 4th position and at the end?
`\'(\'*\', \'*\', \'*\', \'"0\', \'0\', \'7\', \'3\', \'0"\')\'.']}`

**Comment by funkyfuture** [comment] 2019-03-01 16:59
in order to replicate what you experience i need the information how you configure the container in question. please post the `docker-compose.yml`, your command call or whatever else you're doing.

also, complete logs at debug level are always helpful.

**Comment by qmnonic** [comment] 2019-03-01 20:44
relevant parts of the docker-compose.yml
```
  # execute jobs in this container, timezone is UTC
  shiny-jobs:
    container_name: shiny-jobs
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    user: 'root'
    volumes:
       ... stuff here ...
    environment:
      - R_LIBS='/srv/library'
    labels:
      - deck-chores.refresh.command=/bin/sh -c "cd /srv/server/app; update_data.sh"
      - deck-chores.refresh.cron=* * * * * 8 0 0
      - deck-chores.refresh.user=root

  # cron jobs..
  deck-chores:
    image: funkyfuture/deck-chores:0.3
    container_name: deck-chores
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TIMEZONE: UTC
```

I don't have debug logs, the logs above should be enough.
I'm fairly certain cron won't work in any configuration.

**Comment by funkyfuture** [comment] 2019-03-03 19:37
i can't reproduce the behaviour you're describing.

```
$ cat /etc/issue
Ubuntu 18.10 \n \l

$ docker --version
Docker version 18.09.3, build 774a1f4
$ docker-compose --version
docker-compose version 1.23.1, build b02f130
$ cat docker-compose.yml 
foo:
    image: busybox
    restart: unless-stopped
    command: tail -f /dev/null
    labels:
      - deck-chores.ham.command=echo ""
      - deck-chores.ham.cron=* * * * * 8 0 0
      - deck-chores.spam.command=echo ""
      - deck-chores.spam.cron=8 0 0
```

`deck-chores` logs this:

```
2019-03-03 20:36:13,325|DEBUG   |Parsing labels: {'com.docker.compose.config-hash': '11f788306bd25086b9f7dc9c4002ce714fd09519801a5ad3ff28b6310d65d0c6', 'com.docker.compose.container-number': '1', 'com.docker.compose.oneoff': 'False', 'com.docker.compose.project': 'tmp', 'com.docker.compose.service': 'foo', 'com.docker.compose.slug': '673dab6caaced03ce58a72d67836c3c43059017519e7acc85cd360b7ba8a7fc', 'com.docker.compose.version': '1.23.1', 'deck-chores.ham.command': 'echo ""', 'deck-chores.ham.cron': '* * * * * 8 0 0', 'deck-chores.spam.command': 'echo ""', 'deck-chores.spam.cron': '8 0 0'}
2019-03-03 20:36:13,325|DEBUG   |Considering labels for service id: {'com.docker.compose.project': 'tmp', 'com.docker.compose.service': 'foo'}
2019-03-03 20:36:13,325|DEBUG   |Parsed & resolved container flags: image,service
2019-03-03 20:36:13,336|DEBUG   |Considering labels for job definitions: {'deck-chores.ham.command': 'echo ""', 'deck-chores.ham.cron': '* * * * * 8 0 0', 'deck-chores.spam.command': 'echo ""', 'deck-chores.spam.cron': '8 0 0'}
2019-03-03 20:36:13,336|DEBUG   |Job definitions: defaultdict(<class 'dict'>, {'ham': {'command': 'echo ""', 'cron': '* * * * * 8 0 0'}, 'spam': {'command': 'echo ""', 'cron': '8 0 0'}})
2019-03-03 20:36:13,336|DEBUG   |Processing ham
2019-03-03 20:36:13,349|DEBUG   |Normalized definition: {'command': 'echo ""', 'name': 'ham', 'environment': {}, 'jitter': None, 'max': 1, 'timezone': 'UTC', 'trigger': (<class 'apscheduler.triggers.cron.CronTrigger'>, ('*', '*', '*', '*', '*', '8', '0', '0'))}
2019-03-03 20:36:13,349|DEBUG   |Processing spam
2019-03-03 20:36:13,353|DEBUG   |Normalized definition: {'command': 'echo ""', 'name': 'spam', 'environment': {}, 'jitter': None, 'max': 1, 'timezone': 'UTC', 'trigger': (<class 'apscheduler.triggers.cron.CronTrigger'>, ('*', '*', '*', '*', '*', '8', '0', '0'))}
2019-03-03 20:36:13,353|DEBUG   |Assigning service id: 3baef7d8-7a69-57ec-9228-80d2a07817a9
2019-03-03 20:36:13,353|INFO    |Locking service: 3baef7d8-7a69-57ec-9228-80d2a07817a9
2019-03-03 20:36:13,357|DEBUG   |Adding jobs for tmp_foo_1_673dab6caace.
2019-03-03 20:36:13,358|INFO    |Added 'ham' for tmp_foo_1_673dab6caace
2019-03-03 20:36:13,358|INFO    |Added 'spam' for tmp_foo_1_673dab6caace
2019-03-03 20:36:13,358|DEBUG   |Finished inspection of running containers.
2019-03-03 20:36:13,359|INFO    |Added job "exec_job" to job store "default"
2019-03-03 20:36:13,360|INFO    |Added job "exec_job" to job store "default"
```

**Comment by funkyfuture** [comment] 2019-10-05 15:30
closing due to missing feedback.

**Closed by funkyfuture** 2019-10-05 15:30 UTC
Labels: feedback pending
